name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

jobs:
  tests:
    name: integration-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker setup
        run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics=true --master-key='masterKey'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Build project
        run: yarn build
      - name: Run env tests
        run: yarn test:env
      - name: Run env tests
        run: yarn test:env


  style:
    name: style-check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Tests style
        run: yarn lint

  builds:
    name: playground-builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run Playgrounds Builds
        run: yarn test:playgrounds
